language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - git clone https://github.com/pythonjobs/template.git ../template
  - pip install -r ../template/requirements.txt
script: ../template/build.py .
